name: build-app
on: [push]
jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
      - uses: actions/checkout@v2
      - name: Print current directory
      - run: pwd
      - name: List files
      - run: ls
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: bats -v